name: smh
description: Demonstrates how to use the fijkplayer plugin.
publish_to: "none"
version: 0.4.0
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # flutter_ijkplayer: ^0.3.5+1
  oktoast: ^2.3.0
  photo: ^0.3.4
  flutter_swiper: ^1.1.6
  flutter_banner_swiper: ^0.1.4
  http: ^0.12.0+4
  dio: ^3.0.8
  json_annotation: ^3.0.1
  device_info: ^0.4.2+4
  flutter_progress_button: ^0.6.4
  fluttertoast: ^3.1.3
  shared_preferences: ^0.5.6+2
  event_bus: ^1.1.1
  cached_network_image: ^2.0.0
  date_format: ^1.0.8
  # flutter_webview_plugin: ^0.3.10+1
  webview_flutter: ^0.3.19+9
  http_client: ^1.3.1
  url_launcher: ^5.4.1
  flutter_downloader: ^1.4.1
  flutter_markdown: ^0.3.4
  # flutter_tencentplayer_plus: ^0.1.0
  permission_handler: ^4.2.0+hotfix.3
  progress_dialog: ^1.2.0
  open_file: ^3.0.1
  flutter_slidable: ^0.5.4
  image_picker: ^0.6.3+4
  zefyr:
    git:
      url: git://github.com/masewo/zefyr.git
      path: packages/zefyr/
  # lpinyin: ^1.0.9
  flutter_forbidshot: 0.0.2
  screen: 0.0.5
  flutter_svg: ^0.17.3+1
  # fijkplayer:
  #   git:
  #     url: https://github.com/befovy/fijkplayer.git
  #     ref: develop
  fijkplayer:
    git:
      url: https://github.com/befovy/fijkplayer.git
      ref: develop # can be replaced to branch or tag name
  firebase_admob: ^0.9.2+1
  streaming_shared_preferences: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.5
  build_runner: ^1.7.3

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/avatar/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
